
import java.awt.Desktop;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.net.URLEncoder;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author SOHAIB MASOOD
 */
public class AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();
    }
 String user = "root";
    String db_password = "";
    String URL = "jdbc:mysql://localhost:3306/signup";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lout_btn = new javax.swing.JButton();
        hire_btn = new javax.swing.JButton();
        edit_btn = new javax.swing.JButton();
        u_list_btn = new javax.swing.JButton();
        feed_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        admin_tabs = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        u_list_tb = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        find_tf = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        find_table = new javax.swing.JTable();
        findu_btn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        psd_find = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        hire_email = new javax.swing.JTextField();
        hire_btn_em = new javax.swing.JButton();
        hire_name = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        fb_table = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        rs5_pb = new javax.swing.JProgressBar();
        rs1_pb = new javax.swing.JProgressBar();
        rs2_pb = new javax.swing.JProgressBar();
        rs3_pb = new javax.swing.JProgressBar();
        rs4_pb = new javax.swing.JProgressBar();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        rs1_l4 = new javax.swing.JLabel();
        rs1_l1 = new javax.swing.JLabel();
        rs1_l2 = new javax.swing.JLabel();
        rs1_l3 = new javax.swing.JLabel();
        rs1_l5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 102, 204));
        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText(" Welcome To Admin Panel");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 470, 40));

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\BSSE Semester 4\\Object Oriented Software Engneering\\Lab\\CV Building Application\\admin.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 75, -1));

        lout_btn.setBackground(new java.awt.Color(0, 102, 204));
        lout_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lout_btn.setForeground(new java.awt.Color(255, 255, 255));
        lout_btn.setText("Logout");
        lout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lout_btnActionPerformed(evt);
            }
        });
        jPanel1.add(lout_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 130, 40));

        hire_btn.setBackground(new java.awt.Color(0, 102, 204));
        hire_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hire_btn.setForeground(new java.awt.Color(255, 255, 255));
        hire_btn.setText("Hire User");
        hire_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hire_btnActionPerformed(evt);
            }
        });
        jPanel1.add(hire_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 130, 40));

        edit_btn.setBackground(new java.awt.Color(0, 102, 204));
        edit_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        edit_btn.setForeground(new java.awt.Color(255, 255, 255));
        edit_btn.setText("Edit User");
        edit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_btnActionPerformed(evt);
            }
        });
        jPanel1.add(edit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 130, 40));

        u_list_btn.setBackground(new java.awt.Color(0, 102, 204));
        u_list_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        u_list_btn.setForeground(new java.awt.Color(255, 255, 255));
        u_list_btn.setText("User List");
        u_list_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_list_btnActionPerformed(evt);
            }
        });
        jPanel1.add(u_list_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 130, 40));

        feed_btn.setBackground(new java.awt.Color(0, 102, 204));
        feed_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        feed_btn.setForeground(new java.awt.Color(255, 255, 255));
        feed_btn.setText("Feedbacks");
        feed_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feed_btnActionPerformed(evt);
            }
        });
        jPanel1.add(feed_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 130, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 450));

        jLabel5.setBackground(new java.awt.Color(0, 102, 204));
        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\BSSE Semester 4\\Object Oriented Software Engneering\\Lab\\CV Building Application\\LP4.jpg")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -320, 690, 390));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        u_list_tb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        u_list_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Email", "Gender"
            }
        ));
        u_list_tb.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(u_list_tb);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 320));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 204));
        jLabel4.setText("Logged-In Users List");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 240, 40));

        jButton1.setBackground(new java.awt.Color(0, 102, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 100, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\BSSE Semester 4\\Object Oriented Software Engneering\\Lab\\CV Building Application\\LP4.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-270, 320, 760, 60));

        admin_tabs.addTab("tab1", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 204));
        jLabel6.setText(" User Password");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 150, 40));
        jPanel3.add(find_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 320, 40));

        find_table.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        find_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Gender", "Email", "password"
            }
        ));
        jScrollPane2.setViewportView(find_table);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 490, 60));

        findu_btn.setBackground(new java.awt.Color(0, 102, 204));
        findu_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        findu_btn.setForeground(new java.awt.Color(255, 255, 255));
        findu_btn.setText("Find");
        findu_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findu_btnActionPerformed(evt);
            }
        });
        jPanel3.add(findu_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 100, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 204));
        jLabel7.setText(" User First Name");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 150, 40));
        jPanel3.add(psd_find, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 320, 40));

        jButton2.setBackground(new java.awt.Color(0, 102, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 110, 40));

        jButton3.setBackground(new java.awt.Color(0, 102, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 120, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\BSSE Semester 4\\Object Oriented Software Engneering\\Lab\\CV Building Application\\LP4.jpg")); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-420, 320, 910, 60));

        admin_tabs.addTab("tab2", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(hire_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 270, 40));

        hire_btn_em.setBackground(new java.awt.Color(0, 102, 204));
        hire_btn_em.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hire_btn_em.setForeground(new java.awt.Color(255, 255, 255));
        hire_btn_em.setText("Send Offer");
        hire_btn_em.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hire_btn_emActionPerformed(evt);
            }
        });
        jPanel4.add(hire_btn_em, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 150, 40));
        jPanel4.add(hire_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 270, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 204));
        jLabel10.setText("Email");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 70, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 204));
        jLabel12.setText("User Name");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 120, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon("D:\\BSSE Semester 4\\Object Oriented Software Engneering\\Lab\\CV Building Application\\LP4.jpg")); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, 300, 670, 80));

        admin_tabs.addTab("tab3", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fb_table.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        fb_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Rating", "Feeback"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(fb_table);

        jPanel5.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 130));

        jButton4.setBackground(new java.awt.Color(0, 102, 204));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 110, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 204));
        jLabel11.setText("Users Feedbacks ");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon("D:\\BSSE Semester 4\\Object Oriented Software Engneering\\Lab\\CV Building Application\\LP4.jpg")); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-280, 320, 780, 60));

        jLabel14.setBackground(new java.awt.Color(0, 102, 204));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 204));
        jLabel14.setText("Rating Progress");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 150, -1));

        rs5_pb.setForeground(new java.awt.Color(0, 102, 204));
        jPanel5.add(rs5_pb, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 260, 20));

        rs1_pb.setForeground(new java.awt.Color(0, 102, 204));
        jPanel5.add(rs1_pb, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 260, 20));

        rs2_pb.setForeground(new java.awt.Color(0, 102, 204));
        jPanel5.add(rs2_pb, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 260, 20));

        rs3_pb.setForeground(new java.awt.Color(0, 102, 204));
        jPanel5.add(rs3_pb, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 260, 20));

        rs4_pb.setForeground(new java.awt.Color(0, 102, 204));
        jPanel5.add(rs4_pb, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 260, 20));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 204));
        jLabel15.setText("Five Stars");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 285, 100, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 204));
        jLabel16.setText("One Stars");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 165, 100, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 204));
        jLabel17.setText("Two Stars");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 195, 100, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 204));
        jLabel18.setText("Three Stars");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 100, 20));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 204));
        jLabel19.setText("Four Stars");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 100, 20));

        rs1_l4.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        rs1_l4.setForeground(new java.awt.Color(0, 102, 204));
        jPanel5.add(rs1_l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 60, 20));

        rs1_l1.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        rs1_l1.setForeground(new java.awt.Color(0, 102, 204));
        jPanel5.add(rs1_l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 60, 20));

        rs1_l2.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        rs1_l2.setForeground(new java.awt.Color(0, 102, 204));
        jPanel5.add(rs1_l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 60, 20));

        rs1_l3.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        rs1_l3.setForeground(new java.awt.Color(0, 102, 204));
        jPanel5.add(rs1_l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 60, 20));

        rs1_l5.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        rs1_l5.setForeground(new java.awt.Color(0, 102, 204));
        jPanel5.add(rs1_l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 60, 20));

        admin_tabs.addTab("tab4", jPanel5);

        getContentPane().add(admin_tabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 490, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void u_list_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_list_btnActionPerformed
        admin_tabs.setSelectedIndex(0);
         try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con  = DriverManager.getConnection(URL, user, db_password);
            String user_data = "Select first_name, last_name, email, gender From uinfo11 ";
            PreparedStatement ps = con.prepareStatement(user_data);
            ResultSet rs = ps.executeQuery();
         
               while(rs.next()){
                String fname = rs.getString("first_name");
                String lname = rs.getString("last_name");
                String email = rs.getString("email");
                String gen = rs.getString("gender");
                String [] list = {fname, lname, email, gen};
                DefaultTableModel dtm = (DefaultTableModel) u_list_tb.getModel();
                dtm.addRow(list);

            }
            
            
         }
         catch (ClassNotFoundException ex) {
            Logger.getLogger(signup.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
           
        }
        
        
    }//GEN-LAST:event_u_list_btnActionPerformed

    private void lout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lout_btnActionPerformed
       setVisible(false);
       AdminLogin al = new AdminLogin();
       al.setVisible(true);
    }//GEN-LAST:event_lout_btnActionPerformed

    private void edit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_btnActionPerformed
        admin_tabs.setSelectedIndex(1);
    }//GEN-LAST:event_edit_btnActionPerformed

    private void hire_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hire_btnActionPerformed
        admin_tabs.setSelectedIndex(2);
    }//GEN-LAST:event_hire_btnActionPerformed

    private void feed_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feed_btnActionPerformed
        admin_tabs.setSelectedIndex(3);
       
         try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con  = DriverManager.getConnection(URL, user, db_password);
            String user_data = "Select feedback, User_Name, rating From feedback ";
            PreparedStatement ps;
            ps= con.prepareStatement(user_data);
            ResultSet rs;
            rs = ps.executeQuery();
            
                 while(rs.next()){
                String feedback = rs.getString("feedback");
                String User_Name = rs.getString("User_Name");
                String rating = rs.getString("rating");
                
                String [] fb_list = {User_Name, rating, feedback};
                DefaultTableModel dtm = (DefaultTableModel) fb_table.getModel();
                dtm.addRow(fb_list);
            }
               
            String tb_cnt = "Select * From feedback";
            ps=con.prepareStatement(tb_cnt);
           rs = ps.executeQuery();
            double count =0;
            while(rs.next()){
                count++;   
            }
            
            String rs1_cnt = "Select * From feedback where rating = 1";
            ps = con.prepareStatement(rs1_cnt);
            rs = ps.executeQuery();
            double rs1_count=0;
            while(rs.next()){
                rs1_count++;
            }
            String rs2_cnt = "Select * From feedback where rating = 2";
            ps = con.prepareStatement(rs2_cnt);
            rs = ps.executeQuery();
            double rs2_count=0;
            while(rs.next()){
                rs2_count++;
            }
            String rs3_cnt = "Select * From feedback where rating = 3";
            ps = con.prepareStatement(rs3_cnt);
            rs = ps.executeQuery();
            double rs3_count=0;
            while(rs.next()){
                rs3_count++;
            }
            String rs4_cnt = "Select * From feedback where rating = 4";
            ps = con.prepareStatement(rs4_cnt);
            rs = ps.executeQuery();
            double rs4_count=0;
            while(rs.next()){
                rs4_count++;
            }
            String rs5_cnt = "Select * From feedback where rating = 5";
            ps = con.prepareStatement(rs5_cnt);
            rs = ps.executeQuery();
            double rs5_count=0;
            while(rs.next()){
                rs5_count++;
            }
            double rs1_per = (rs1_count/count)*100;
            double rs2_per = (rs2_count/count)*100;
            double rs3_per = (rs3_count/count)*100;
            double rs4_per = (rs4_count/count)*100;
            double rs5_per = (rs5_count/count)*100;
            rs1_pb.setValue((int)rs1_per);
            rs2_pb.setValue((int)rs2_per);
            rs3_pb.setValue((int)rs3_per);
            rs4_pb.setValue((int)rs4_per);
            rs5_pb.setValue((int)rs5_per);
            rs1_l1.setText(String.valueOf((int)rs1_per)+"%");
            rs1_l2.setText(String.valueOf((int)rs2_per)+"%");
            rs1_l3.setText(String.valueOf((int)rs3_per)+"%");
            rs1_l4.setText(String.valueOf((int)rs4_per)+"%");
            rs1_l5.setText(String.valueOf((int)rs5_per)+"%");
         }
         catch (ClassNotFoundException ex) {
            Logger.getLogger(signup.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_feed_btnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) u_list_tb.getModel();
        dtm.setRowCount(0);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void findu_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findu_btnActionPerformed
        String fname = find_tf.getText();
        char [] psd = psd_find.getPassword();
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con  = DriverManager.getConnection(URL, user, db_password);
            String user_data = "Select first_name, last_name, email, gender"
                    + " from uinfo11 where first_name = '"+fname+"' and password = '"+Arrays.toString(psd)+"'";
                    
            PreparedStatement ps = con.prepareStatement(user_data);
            ResultSet rs = ps.executeQuery();
            
                 if(rs.next()){
                          String fname_db = rs.getString("first_name");
                String lname = rs.getString("last_name");
                String email = rs.getString("email");
                String gen = rs.getString("gender");
                String [] list = {fname_db, lname, gen, email, Arrays.toString(psd)};
                DefaultTableModel dtm = (DefaultTableModel) find_table.getModel();
                dtm.addRow(list);
                
            }
            else{
                 JOptionPane.showMessageDialog(this, "Invalid User name or password Please Try Again", "Error", JOptionPane.ERROR_MESSAGE);
                 find_tf.setText("");
                 psd_find.setText("");
                     }
         
         }
         catch (ClassNotFoundException ex) {
            Logger.getLogger(signup.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_findu_btnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) find_table.getModel();
        dtm.setRowCount(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       DefaultTableModel dtm = (DefaultTableModel) find_table.getModel();
       try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con  = DriverManager.getConnection(URL, user, db_password);
       String query = "update uinfo11 set first_name = ?, last_name = ?, gender = ?, email = ?,"
               + " password = ? where first_name = '"+find_tf.getText()+"'";
            PreparedStatement pst = con.prepareStatement(query);
           
                pst.setString(1, dtm.getValueAt(0, 0).toString());
                pst.setString(2, dtm.getValueAt(0, 1).toString());
                pst.setString(3, dtm.getValueAt(0, 2).toString());
                pst.setString(4, dtm.getValueAt(0, 3).toString());
                pst.setString(5, dtm.getValueAt(0, 4).toString());
                pst.executeUpdate();
           
            JOptionPane.showMessageDialog(null, "User Login Informations Updated Successfully");
            pst.close();
            con.close();
       } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) fb_table.getModel();
        dtm.setRowCount(0);
        rs1_pb.setValue(0);rs2_pb.setValue(0);rs3_pb.setValue(0);
        rs4_pb.setValue(0);rs5_pb.setValue(0);
        rs1_l1.setText("");rs1_l2.setText("");rs1_l3.setText("");
        rs1_l4.setText("");rs1_l5.setText("");
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void hire_btn_emActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hire_btn_emActionPerformed
        
        String to = hire_email.getText();
        String Name = hire_name.getText();
        // Subject of the email
        String subject = "Job Offered";
        // Body of the email
        String body = "Respective Sir\nMr./Ms."+ Name+"\nI hope you will be fine, today you have created your"
                + " resume by using our app, which we have posted on our website, "
                + "on which you have received a job offer from the Apple company, "
                + "for the details of which you can visit our website. You can visit the site\n" +
                "Website link: file:///D:/BSSE%20Semester%201/Intro%20To%20ICT/Web%20Development/my%20work/Bootstrap%20website/index.html";
       
        // Create the mailto URI
        
try {
    
            subject = URLEncoder.encode(subject, "UTF-8");
            body = URLEncoder.encode(body, "UTF-8");
            body = body.replace("+", "_");
            subject=subject.replace("+", "_");
            URI mailto = new URI("mailto:" + to + "?subject=" + subject + "&body=" + body);
            Desktop.getDesktop().browse(mailto);
            
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        } catch (URISyntaxException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_hire_btn_emActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane admin_tabs;
    private javax.swing.JButton edit_btn;
    private javax.swing.JTable fb_table;
    private javax.swing.JButton feed_btn;
    private javax.swing.JTable find_table;
    private javax.swing.JTextField find_tf;
    private javax.swing.JButton findu_btn;
    private javax.swing.JButton hire_btn;
    private javax.swing.JButton hire_btn_em;
    private javax.swing.JTextField hire_email;
    private javax.swing.JTextField hire_name;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton lout_btn;
    private javax.swing.JPasswordField psd_find;
    private javax.swing.JLabel rs1_l1;
    private javax.swing.JLabel rs1_l2;
    private javax.swing.JLabel rs1_l3;
    private javax.swing.JLabel rs1_l4;
    private javax.swing.JLabel rs1_l5;
    private javax.swing.JProgressBar rs1_pb;
    private javax.swing.JProgressBar rs2_pb;
    private javax.swing.JProgressBar rs3_pb;
    private javax.swing.JProgressBar rs4_pb;
    private javax.swing.JProgressBar rs5_pb;
    private javax.swing.JButton u_list_btn;
    private javax.swing.JTable u_list_tb;
    // End of variables declaration//GEN-END:variables
}
